/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeviceId = string;
export interface DeviceInfo {
  'id' : DeviceId,
  'signalStrength' : bigint,
  'name' : string,
  'connected' : boolean,
}
export type MotorId = bigint;
export interface MotorStatus {
  'id' : MotorId,
  'temperature' : TempCelsius,
  'isOn' : boolean,
}
export type TempCelsius = number;
export interface TempDataPoint {
  'temperature' : TempCelsius,
  'minutesFromNow' : bigint,
}
export interface TempPrediction {
  'motorId' : MotorId,
  'horizon' : bigint,
  'dataPoints' : Array<TempDataPoint>,
}
export interface TemperatureAlert {
  'motorId' : MotorId,
  'threshold' : TempCelsius,
  'temperature' : TempCelsius,
  'message' : string,
}
export interface _SERVICE {
  'getDevices' : ActorMethod<[], Array<DeviceInfo>>,
  'getMotors' : ActorMethod<[], Array<MotorStatus>>,
  'getTempPrediction' : ActorMethod<[bigint, bigint], TempPrediction>,
  'getTemperatureAlerts' : ActorMethod<[], Array<TemperatureAlert>>,
  'refreshDevices' : ActorMethod<[], Array<DeviceInfo>>,
  'switchMotor' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];