/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceId = IDL.Text;
export const DeviceInfo = IDL.Record({
  'id' : DeviceId,
  'signalStrength' : IDL.Nat,
  'name' : IDL.Text,
  'connected' : IDL.Bool,
});
export const MotorId = IDL.Nat;
export const TempCelsius = IDL.Float64;
export const MotorStatus = IDL.Record({
  'id' : MotorId,
  'temperature' : TempCelsius,
  'isOn' : IDL.Bool,
});
export const TempDataPoint = IDL.Record({
  'temperature' : TempCelsius,
  'minutesFromNow' : IDL.Nat,
});
export const TempPrediction = IDL.Record({
  'motorId' : MotorId,
  'horizon' : IDL.Nat,
  'dataPoints' : IDL.Vec(TempDataPoint),
});
export const TemperatureAlert = IDL.Record({
  'motorId' : MotorId,
  'threshold' : TempCelsius,
  'temperature' : TempCelsius,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'getDevices' : IDL.Func([], [IDL.Vec(DeviceInfo)], ['query']),
  'getMotors' : IDL.Func([], [IDL.Vec(MotorStatus)], []),
  'getTempPrediction' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [TempPrediction],
      ['query'],
    ),
  'getTemperatureAlerts' : IDL.Func([], [IDL.Vec(TemperatureAlert)], ['query']),
  'refreshDevices' : IDL.Func([], [IDL.Vec(DeviceInfo)], []),
  'switchMotor' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceId = IDL.Text;
  const DeviceInfo = IDL.Record({
    'id' : DeviceId,
    'signalStrength' : IDL.Nat,
    'name' : IDL.Text,
    'connected' : IDL.Bool,
  });
  const MotorId = IDL.Nat;
  const TempCelsius = IDL.Float64;
  const MotorStatus = IDL.Record({
    'id' : MotorId,
    'temperature' : TempCelsius,
    'isOn' : IDL.Bool,
  });
  const TempDataPoint = IDL.Record({
    'temperature' : TempCelsius,
    'minutesFromNow' : IDL.Nat,
  });
  const TempPrediction = IDL.Record({
    'motorId' : MotorId,
    'horizon' : IDL.Nat,
    'dataPoints' : IDL.Vec(TempDataPoint),
  });
  const TemperatureAlert = IDL.Record({
    'motorId' : MotorId,
    'threshold' : TempCelsius,
    'temperature' : TempCelsius,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'getDevices' : IDL.Func([], [IDL.Vec(DeviceInfo)], ['query']),
    'getMotors' : IDL.Func([], [IDL.Vec(MotorStatus)], []),
    'getTempPrediction' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [TempPrediction],
        ['query'],
      ),
    'getTemperatureAlerts' : IDL.Func(
        [],
        [IDL.Vec(TemperatureAlert)],
        ['query'],
      ),
    'refreshDevices' : IDL.Func([], [IDL.Vec(DeviceInfo)], []),
    'switchMotor' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };